# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49829cc5478106f8d346843504cc935b7f1691fd63b69386d62f0c8573faf4f3230ce4e3041cd5fccc5bd47d6804148c189f7139d0b1ddd3e7c2ba53209acdcf

test:
  secret_key_base: b546a2e947cf3ef7ff766d99702ee5791660a0e5215089dbab800d8cea595c8fe1ecc2e2b1549064149cff5d85bb7056f49ab9e6b62157c3ece31fd2818174a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
